CREATE TABLE "NEWS_BOARD" (
	"P_NO"	NUMBER		NOT NULL,
	"P_WRITER"	VARCHAR2(200)		NOT NULL,
	"P_TITLE"	VARCHAR2(200)		NOT NULL,
	"P_CONTENTS"	CLOB		NOT NULL,
	"P_REG_DATE"	VARCHAR2(200)	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')	NOT NULL,
	"P_HIT"	NUMBER	DEFAULT 0	NOT NULL,
	"P_CATEGORY"	VARCHAR2(200)		NULL
);

SELECT * FROM NEWS_BOARD;

COMMIT;